#!/bin/bash
docker_apt_repo='https://download.docker.com/linux/ubuntu'
curl -fsSL "${docker_apt_repo}/gpg" | apt-key add -
os="$(lsb_release -cs)"
add-apt-repository "deb [arch=amd64] $docker_apt_repo $os stable"
apt-get update
apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

config='/etc/docker/daemon.json'
if [[ -e "$config" ]]; then
  sed -i -e 's/{/{ "experimental": true, /' "$config"
else
  echo '{ "experimental": true }' | tee "$config"
fi
systemctl restart docker

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

docker buildx create --use --name mybuilder
docker buildx inspect --bootstrap
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -f $DOCKERFILE_PATH -t $IMAGE_NAME .
